### ISSUE TITLE
Crash with MixinBooter 9.1, Forge 14.23.5.2860

### ISSUE THREAD

**Issue by erplsf** [CleanroomMC/MixinBooter#76]
Couldn't find any similar issue on the issue tracker - my client crashes when I add latest MixinBooter 9.1 for [nae2](https://www.curseforge.com/minecraft/mc-mods/nae2) mod. Modpack is FTB Interactions (latest version from the FTB App with updated Forge and AE2 Unofficial Extended Life).
[logs.zip](https://github.com/CleanroomMC/MixinBooter/files/14550537/logs.zip)

**Comment by erplsf** [comment]
Short excerpt out of crash log:
```
java.lang.RuntimeException: java.lang.NoSuchMethodException: org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(org.spongepowered.asm.mixin.MixinEnvironment)
    at net.minecraftforge.fml.common.Loader.handler$zzb000$beforeConstructingMods(Loader.java:1149)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchMethodException: org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(org.spongepowered.asm.mixin.MixinEnvironment)
    at java.lang.Class.getDeclaredMethod(Class.java:2130)
    at net.minecraftforge.fml.common.Loader.handler$zzb000$beforeConstructingMods(Loader.java:1145)
    ... 14 more
```

**Comment by KorewaLidesu** [comment]
Please check this out https://github.com/CleanroomMC/MixinBooter/issues/34

**Comment by erplsf** [comment]
Thank you very much, it has worked! Maybe add this fix to the README?
