### ISSUE TITLE
`CrashReportMixin` crash

### ISSUE THREAD

**Issue by SettingDust** [CleanroomMC/MixinBooter#98]
https://github.com/CleanroomMC/MixinBooter/commit/f083c7bb4ebde1511b477dfd5d03fb09b3ae7d73

```
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:      Suppressed: com.llamalad7.mixinextras.sugar.impl.SugarApplicationException: Failed to validate sugar @Local Throwable on method afterStackTracePopulation(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V from mixin mixin.mixinbooter.init.json:CrashReportMixin from owner mixinbooter in target method net/minecraft/crash/CrashReport::func_71498_d()Ljava/lang/String; at instruction InjectionNode[Insn [ARETURN] ]
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:              at com.llamalad7.mixinextras.sugar.impl.SugarInjector.validateApplicators(SugarInjector.java:183)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:              at com.llamalad7.mixinextras.sugar.impl.SugarInjector.prepareSugar(SugarInjector.java:161)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:              at com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.prepare(SugarWrapperImpl.java:71)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:              at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.prepare(WrapperInjectionInfo.java:64)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:              at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1407)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:              at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:              at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:              ... 29 more
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:      Caused by: com.llamalad7.mixinextras.sugar.impl.SugarApplicationException: Invalid implicit variable discriminator:
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:              at com.llamalad7.mixinextras.sugar.impl.LocalSugarApplicator.validate(LocalSugarApplicator.java:47)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:              at com.llamalad7.mixinextras.sugar.impl.SugarInjector.validateApplicators(SugarInjector.java:179)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:710]:              ... 35 more
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:704]:      Caused by: org.spongepowered.asm.mixin.injection.modify.InvalidImplicitDiscriminatorException: Found 2 candidate variables but exactly 1 is required.
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:704]:              at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findImplicitLocal(LocalVariableDiscriminator.java:370)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:704]:              at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findLocal(LocalVariableDiscriminator.java:341)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:704]:              at com.llamalad7.mixinextras.sugar.impl.LocalSugarApplicator.validate(LocalSugarApplicator.java:43)
[15:31:09] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:704]:              ... 36 more
```

导出的类也确实没有第二个
![图片](https://github.com/user-attachments/assets/6bbcd06a-7b60-486d-b37d-ba47b2b676cc)

我尝试在本地修改 print true，但是找不到 `MixinContextQuery` 类，构建不了

**Comment by Rongmario** [comment]
I don't crash in dev or in large modpacks, but I've fixed it to stop it from breaking easily, also, `MixinContextQuery` doesn't exist after MixinBooter 10+, not sure why you can't build it.

**Comment by SettingDust** [comment]
麻烦发布一下这个版本？
